### ISSUE TITLE
Manage Apps should link to documentation

### ISSUE THREAD

**Issue by mittonk** [Yelp/yelp-api-v3#1]
I don't see any links from the main preview site:
* https://www.yelp.com/developers/v3/preview/manage_app 

to the documentation:
* https://github.com/Yelp/yelp-api-v3

Feels like we should add some.

**Comment by mittonk** [comment]
Ah, there is a docs link on https://www.yelp.com/developers/v3/preview .

**Comment by guangyang** [comment]
It is still a good idea to provide a link to v3 documentation from the manage app page.

**Comment by tomelm** [comment]
Added a link to the bottom of the page
