### ISSUE TITLE
/businesses/{id} hours[x].open[x].day meaning

### ISSUE THREAD

**Issue by wpohl** [Yelp/yelp-api-v3#18]
The documentation stated:
"From 0 to 6, representing day of the week from Sunday to Saturday. "
But my experience is that 0 represents Monday and 6 Sunday.
Seen with businessId from Germany (echtasien-hamburg) and London (joe-allen-london).
What is right?

**Comment by mittonk** [comment]
I concur, the API is returning Monday as day 0, while the docs say Sunday is day 0:
* https://github.com/Yelp/yelp-api-v3/blob/master/docs/api-references/businesses-id.md

**Comment by guangyang** [comment]
Thanks for reporting this, @wpohl. I've fixed it in the doc.
