### ISSUE TITLE
/businesses/{id}/reviews missing date/time

### ISSUE THREAD

**Issue by wpohl** [Yelp/yelp-api-v3#19]
A date/time is missing in the API. Any plans to support his soon?

**Comment by guangyang** [comment]
Could you please help us understand why this information important for you? Want to make sure we understand your scenario.

**Comment by wpohl** [comment]
We will show when the review was written. That give the reader more context informations.

**Comment by brentsch319** [comment]
Timestamps on reviews (which are in the V2 excerpts) help provide relevance for users, as I will give more credence to a review that is a month old vs. a review from years ago.

**Comment by collinhundley** [comment]
I'd also like to chime in that date/time is extremely important.

In addition to providing valuable information to the end-user, it's also the only property that can be used to uniquely identify a review.

**Comment by Wirwing** [comment]
+1 for this missing attribute. Without it, users dont know if a review is older, still standing, etc.

**Comment by tomelm** [comment]
Hey everyone! I've pushed out a change that adds a time_created field to the response.
