### ISSUE TITLE
HTTP status 400 could use some details

### ISSUE THREAD

**Issue by mittonk** [Yelp/yelp-api-v3#2]
`https://api.yelp.com/v3/businesses/search?term=food` (missing required `location` parameter) gives a plain HTTP 400 without a body.

It'd be useful to specify which input failed validation (`location`) and why (missing entirely in this case).

**Comment by guangyang** [comment]
Yes, better error message is something we are planning to improve very soon.

**Comment by tomelm** [comment]
@mittonk want to try this again? Things should be a bit improved

**Comment by mittonk** [comment]
```javascript
{
  "error": {
    "description": "Please specify a location or a latitude and longitude",
    "code": "VALIDATION_ERROR"
  }
}
```

Much better, thanks!

**Comment by mittonk** [comment]
Actually, I now get an HTTP 200 with that body.

200 seems weird, I would expect a 400.

**Comment by mittonk** [comment]
Whoops, wrong window, 400 with a nice explanatory body.  Great!
