### ISSUE TITLE
/businesses/{id}/reviews limitations

### ISSUE THREAD

**Issue by wpohl** [Yelp/yelp-api-v3#20]
Which reviews are included into the three that are exposed by the API?
- The newest? 
- most recommended?
From my point of view neither nor but what else.

Any plans to expose more than 3 reviews (even it is three times better than API v2)?

**Comment by tomelm** [comment]
The reviews are sorted by our internal algorithm that takes into account a number of different signals. There's some more info here: http://www.yelp-support.com/article/How-is-the-order-of-reviews-determined?l=en_US
