### ISSUE TITLE
Angular2 / Javascript CORS

### ISSUE THREAD

**Issue by peterpeterparker** [Yelp/yelp-api-v3#21]
Hi,

While implementing your V3 API I face the following CORS problem with my Ionic2/Angular2 application:

XMLHttpRequest cannot load https://api.yelp.com/v3/businesses/search. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 404.

While using the V2 of the API, I was "bypassing" the CORS problem using http.jsonp whish isn't applicable anymore, because the authorization bearer should be added in the header of the GET request (as far as I understood, a Jsonp header can't be modified).

That's why I tried:

     private queryYelp(yelpOAuth:YelpCommunication.YelpOAuthSignature, nextTo:AddressLocation.Location):Promise<{}> { 
        let params:URLSearchParams = new URLSearchParams();  

        params.set('limit', '' + Resources.Constants.Default.YELP.LIMIT);
        params.set('latitude', '' + nextTo.coordinates[0]); 
        params.set('longitude', '' + nextTo.coordinates[1]); 
        params.set('radius', '' + Resources.Constants.Default.YELP.RADIUS); 
        params.set('sort_by', Resources.Constants.Default.YELP.SORT.BEST_MATCHED);   

       let headers:Headers = new Headers();  
       headers.append('Authorization', 'Bearer ' + yelpOAuth.access_token);   
       let options:RequestOptions = new RequestOptions({  
           headers: headers,
                search: params, 
                withCredentials: true 
                });  

        return new Promise((resolve, reject) => {  
           this.http.get(Resources.Constants.Default.YELP.URL, options)  
               .map(res => res.json()) 
                .subscribe((businesses:Yelp.YelpBusiness[]) => {  
                   resolve(businesses); 
                }, (errorResponse:Response) => {  
                         reject(errorResponse);  
                }); 
        }); 
        }

or

private queryYelp(yelpOAuth:YelpCommunication.YelpOAuthSignature, nextTo:AddressLocation.Location):Promise<{}> {
        return new Promise((resolve, reject) => {
            let xhr:XMLHttpRequest = new XMLHttpRequest();

            let formData:FormData = new FormData();
            formData.append('limit', '' + Resources.Constants.Default.YELP.LIMIT);
            formData.append('latitude', '' + nextTo.coordinates[0]);
            formData.append('longitude', '' + nextTo.coordinates[1]);
            formData.append('radius', '' + Resources.Constants.Default.YELP.RADIUS);
            formData.append('sort_by', Resources.Constants.Default.YELP.SORT.BEST_MATCHED);

            xhr.onload = () => {
                console.log("status " + xhr.status);
                if (xhr.readyState === XMLHttpRequest.DONE && xhr.status == 201) {
                    let businesses:Yelp.YelpBusiness[] = JSON.parse(xhr.responseText);
                    resolve(businesses);
                } else {
                    reject();
                }
            };

            xhr.onerror = () => {
                alert('Woops, there was an error making the request.');
            };

            xhr.open("GET", Resources.Constants.Default.YELP.URL, true);
            xhr.setRequestHeader("Authorization", 'Bearer ' + yelpOAuth.access_token);
            xhr.send(formData);
        });
    }

and both solution weren't successful aka both solution leaded to the CORS error listed above.

Did I miss something or how could I query the Yelp API v3 from Ionic2 / Angular2?

Best regards

P.S.: Note that my OAuth access_token isn't exposed. The authentication is generated by my backend.

**Comment by peterpeterparker** [comment]
Within the help of http://stackoverflow.com/questions/38598928/angular2-yelp-api-cors-error I manage to find a solution how to solve that using a proxy in Ionic2.

It's still unclear for me how to solve that problem with Angular2 in case of a website. Should I use a proxy too then?

**Comment by tomelm** [comment]
@peterpeterparker you're correct in regards that we do not allow CORS. I think what you've suggested is the best course of action for the time being

**Comment by rgantla** [comment]
In my experience the plugins worked with http but not with the latest httpClient. Also, configuring the CORS respsonse headers on the server wasn't really an option. So, I created a proxy.conf.json file to act as a proxy server.

Read more about this here: https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/proxy.md

**below is my prox.conf.json file**

    {
      "/posts": {
        "target": "https://example.com",
        "secure": true,
        "pathRewrite": {
        "^/posts": ""
      },
        "changeOrigin": true
      }
    }

**I placed the proxy.conf.json file right next the the package.json file in the same directory**

**then I modified the start command in the package.json file like below**

    "start": "ng serve --proxy-config proxy.conf.json"

now, the http call from my app component is as follows

    return this._http.get('/posts/pictures?method=GetPictures')
    .subscribe((returnedStuff) => {
      console.log(returnedStuff);
    });

Lastly to run my app, I'd have to use **npm start** or **ng serve --proxy-config proxy.conf.json**
