### ISSUE TITLE
businesses/search, sort_by=review_count/rating doesn't return expected result.

### ISSUE THREAD

**Issue by zuchie** [Yelp/yelp-api-v3#24]
Using query string:
"https://api.yelp.com/v3/businesses/search?term=french&latitude=37.786882&longitude=-122.399972&limit=5&sort_by=review_count"

It gives 5 response bodies with review count:
550, 1732, 1315, 1544, 175

Should I expect: 1732, 1544, 1315, 550, 175 ?

Using query string:
"https://api.yelp.com/v3/businesses/search?term=french&latitude=37.786882&longitude=-122.399972&limit=1&sort_by=review_count"

It gives 1 response body with review count:
550

Should I expect: 1732 ?

Same as sort_by=rating. Not sure whether it's a bug or I was using it wrong way. Please take a look. Thanks.

**Comment by tomelm** [comment]
I think this might be related to #27, sorting may be broken

**Comment by tomelm** [comment]
Hey @zuchie! This is fixed now. As I said in #29, the one note on sorting is that we only return 40 businesses when you apply the sort_by parameter.

Also, for sort by rating, it won't be a strict sort but is sorted by the adjusted rating. Quoting this from our previous v2 docs: "The rating sort is not strictly sorted by the rating value, but by an adjusted rating value that takes into account the number of ratings, similar to a bayesian average. This is so a business with 1 rating of 5 stars doesn’t immediately jump to the top."
