### ISSUE TITLE
/businesses/{id}/reviews returning oldest reviews

### ISSUE THREAD

**Issue by brentsch319** [Yelp/yelp-api-v3#27]
In experimentation across several locations the /businesses/{id}/reviews request is returning the three oldest reviews for a location.  In some of these cases I see reviews being returned that are found in the 'not recommended' set of reviews (and for which the returned URL with anchor tag does not work).  An example of the latter are reviews returned for business ID the-remington-club-san-diego.

Note that this behavior is is inconsistent with the answer provided to wpohl on issue #20 (/businesses/{id}/reviews limitations) which stated these would be returned in Yelp sort order.

Ideally a developer could pass an argument requesting sort order (similar to UI experience) which would allow me to show these in Yelp sort order or the newest set of reviews.

**Comment by tomelm** [comment]
(note: the issue I referenced isn't related, I got the number wrong).

I'll look into the current sorting order for reviews and see how we might want to change it. I'll talk to a few people about review sort_by parameter and see what we think.

**Comment by tomelm** [comment]
@brentsch319 this is resolved now! Please note that if you're logged and have friends on Yelp it will return a slightly different order but the API now returns reviews sorted based on logged out usage.
