### ISSUE TITLE
pricing_filter doesn't work

### ISSUE THREAD

**Issue by enwei-canonical** [Yelp/yelp-api-v3#35]
curl --get --include 'https://api.yelp.com/v3/businesses/search?pricing_filter=1&latitude=37.7869&limit=40&locale=en_US&longitude=-122.4000&offset=0' -H 'Authorization:Bearer '
HTTP/1.1 200 OK
Date: Tue, 16 Aug 2016 02:20:48 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 25462
Connection: keep-alive
Set-Cookie: __cfduid=d037183bd6aa06545f447b3c9d8acddb81471314044; expires=Wed, 16-Aug-17 02:20:44 GMT; path=/; domain=.yelp.com; HttpOnly
X-Proxied: 10-64-0-235-uswest1aprod
X-Nginx-Frontend: api
Server: cloudflare-nginx
CF-RAY: 2d3168ac12fb45fc-TPE

{"total": 32792, "businesses": [{"name": "T-We Tea", "url": "https://www.yelp.com/biz/t-we-tea-san-francisco", "coordinates": {"latitude": 37.789574, "longitude": -122.402784}, "image_url": "http://s3-media2.fl.yelpcdn.com/bphoto/sdtJq7aMdlpaU8Sgwl8Xuw/o.jpg", "categories": [{"alias": "tea", "title": "Tea Rooms"}, {"alias": "coffee", "title": "Coffee & Tea"}], "price": "$$", "location": {"zip_code": "94104", "city": "San Francisco", "country": "US", "address2": "50 Post St Level 1", "address3": "", "address1": "Crocker Galleria", "state": "CA"}, "id": "t-we-tea-san-francisco", "rating": 5.0, "phone": "+14155002097", "review_count": 81}, {"name": "Tadu Ethiopian Kitchen", "url": "https://www.yelp.com/biz/tadu-ethiopian-kitchen-san-francisco-3", "coordinates": {"latitude": 37.7847934, "longitude": -122.4141884}, "image_url": "http://s3-media3.fl.yelpcdn.com/bphoto/EapkmG5rpJuy7u8tu01GYA/o.jpg", "categories": [{"alias": "ethiopian", "title": "Ethiopian"}], "price": "$$", "location": {"zip_code": "94102", "city": "San Francisco", "country": "US", "address2": "", "address3": "", "address1": "484 Ellis St", "state": "CA"}, "id": "tadu-ethiopian-kitchen-san-francisco-3", "rating": 4.5, "phone": "+14154096649", "review_count": 336},

The result is the same with that of without pricing_filter. Thanks.

**Comment by tomelm** [comment]
Looking into this

**Comment by tomelm** [comment]
Hey @enwei-canonical, I think this might've been because our documentation was wrong. The parameter should've been called `price_filter` instead of `pricing_filter`. We've recently renamed this parameter though (#42), could you try using `price`?

**Comment by tomelm** [comment]
Closing this, things look like they're working on my side
