### ISSUE TITLE
html content will return sometimes

### ISSUE THREAD

**Issue by enwei-canonical** [Yelp/yelp-api-v3#37]
When I run query "https://api.yelp.com/v3/businesses/search?latitude=37.7869&limit=50&locale=en_US&longitude=-122.4000&offset=50", sometimes html saying gateway time out will return. Below is the content

[error.txt](https://github.com/Yelp/yelp-api-v3/files/424148/error.txt)

**Comment by tomelm** [comment]
Yep, this is a known issue and we're working on it. Will update you when we have it resolved

**Comment by tomelm** [comment]
I believe we've resolved this issue, please let me know if it's still happening though and I'll reopen this
