### ISSUE TITLE
Access_token yelp api 3.0

### ISSUE THREAD

**Issue by NikitaTurakhia** [Yelp/yelp-api-v3#39]
HI,

https://api.yelp.com/oauth2/token. In this url how to get token?
Is token and access_token are same?
Because when I try to send url with myurl+access_token, it give me the error of token_missing

  var request = (HttpWebRequest)WebRequest.Create("https://api.yelp.com/oauth2/token");

                string yelpurl = https://api.yelp.com/v3/autocomplete?text=del&latitude=37.786882&longitude=-122.399972;
               
                
                var postData = "grant_type=client_credentials";
                postData += "&client_id=clientid";
                postData += "&client_secret=clientsecret id";
                var data = Encoding.ASCII.GetBytes(postData);

                request.Method = "POST";
                request.ContentType = "application/x-www-form-urlencoded";

                using (var stream = await Task.Factory.FromAsync<Stream>(request.BeginGetRequestStream, request.EndGetRequestStream, null))
                {
                    stream.Write(data, 0, data.Length);
                }

                var response = (HttpWebResponse)await request.GetResponseAsync();

                var responseString = new StreamReader(response.GetResponseStream()).ReadToEnd();
                 AccessToken _token= JsonConvert.DeserializeObject<AccessToken>(responseString);
                var exires_in = _token.expires_in;
                var token = _token.access_token;
                var token_type = _token.token_type;
                responseString = yelpurl + "&access_token=" + token;

**Comment by tomelm** [comment]
Hey @NikitaTurakhia, that is how you get an access token. It looks like you're passing the access token in as the URL parameter which we don't support. Could you pass it int through the header instead? The tutorial starting from the auth section should be helpful: https://github.com/Yelp/yelp-api-v3/blob/master/docs/tutorials/get-start-yelp-api-v3.md#get-an-access-token

**Comment by mittonk** [comment]
(Same issue also came up in #45 , perhaps with the same person, I wonder if our docs could be clearer.)

**Comment by NikitaTurakhia** [comment]
Hey @mittonk in docs I din't get how to pass the access_token, but now i get and my problem is solved.
