### ISSUE TITLE
open_now_filter does not work

### ISSUE THREAD

**Issue by galskari** [Yelp/yelp-api-v3#40]
Hi,
I am trying to use the open_now_filter=true. Somehow it doesnt work as I get many business that are closed at the time of search.

Example:
https://api.yelp.com/v3/businesses/search?term=florists&latitude=41.885157&longitude=-87.622456&open_now_filter=true

This request was sent on  Tue, 23 Aug 2016 07:03:27 GMT (00:00 PST)
the first result is jolie-fleur-flower-boutique-chicago. This place however is closed at this time https://www.yelp.com/biz/jolie-fleur-flower-boutique-chicago

You can see the the full response attached below

{
  "total": 983,
  "businesses": [
    {
      "location": {
        "address2": null,
        "address1": "444 North Wabash Ave",
        "country": "US",
        "city": "Chicago",
        "state": "IL",
        "address3": "",
        "zip_code": "60611"
      },
      "coordinates": {
        "longitude": -87.6253654,
        "latitude": 41.8912568
      },
      "url": "https://www.yelp.com/biz/jolie-fleur-flower-boutique-chicago",
      "categories": [
        {
          "alias": "florists",
          "title": "Florists"
        }
      ],
      "name": "Jolie Fleur Flower Boutique",
      "image_url": "http://s3-media3.fl.yelpcdn.com/bphoto/98GgeaT3HjNeVIA6gmQuEQ/o.jpg",
      "id": "jolie-fleur-flower-boutique-chicago",
      "phone": "+13123291770",
      "review_count": 37,
      "price": "$$",
      "rating": 5
    },
    {
      "location": {
        "address2": "",
        "address1": "715 N Franklin St",
        "country": "US",
        "city": "Chicago",
        "state": "IL",
        "address3": "",
        "zip_code": "60654"
      },
      "coordinates": {
        "longitude": -87.6355403,
        "latitude": 41.8952674
      },
      "url": "https://www.yelp.com/biz/fleur-de-lis-florist-chicago",
      "categories": [
        {
          "alias": "florists",
          "title": "Florists"
        }
      ],
      "name": "Fleur De Lis Florist",
      "image_url": "http://s3-media3.fl.yelpcdn.com/bphoto/MSf5vt2M6gNW-gxiP_jU1A/o.jpg",
      "id": "fleur-de-lis-florist-chicago",
      "phone": "+13129434444",
      "review_count": 49,
      "price": "$$$",
      "rating": 5
    },
    {
      "location": {
        "address2": null,
        "address1": "1335 S. State St.",
        "country": "US",
        "city": "Chicago",
        "state": "IL",
        "address3": "",
        "zip_code": "60605"
      },
      "coordinates": {
        "longitude": -87.6272792,
        "latitude": 41.8646711
      },
      "url": "https://www.yelp.com/biz/henry-hampton-floral-chicago",
      "categories": [
        {
          "alias": "florists",
          "title": "Florists"
        }
      ],
      "name": "Henry Hampton Floral",
      "image_url": "http://s3-media3.fl.yelpcdn.com/bphoto/rR5F7f6KzmEIuyxEYvjNxg/o.jpg",
      "id": "henry-hampton-floral-chicago",
      "phone": "+13124610066",
      "review_count": 37,
      "price": "$$",
      "rating": 4.5
    },
    {
      "location": {
        "address2": "Ste 1800",
        "address1": "227 W Monroe St",
        "country": "US",
        "city": "Chicago",
        "state": "IL",
        "address3": "",
        "zip_code": "60606"
      },
      "coordinates": {
        "longitude": -87.634728,
        "latitude": 41.880271
      },
      "url": "https://www.yelp.com/biz/a-plus-flowers-and-gifts-chicago",
      "categories": [
        {
          "alias": "florists",
          "title": "Florists"
        }
      ],
      "name": "A Plus Flowers & Gifts",
      "image_url": "http://s3-media2.fl.yelpcdn.com/bphoto/zkkXi8sKVX-n57jb54rpDw/o.jpg",
      "id": "a-plus-flowers-and-gifts-chicago",
      "phone": "+13126069800",
      "review_count": 34,
      "price": "$$",
      "rating": 4.5
    },
    {
      "location": {
        "address2": "",
        "address1": "140 S Wabash Ave",
        "country": "US",
        "city": "Chicago",
        "state": "IL",
        "address3": "",
        "zip_code": "60603"
      },
      "coordinates": {
        "longitude": -87.6262941,
        "latitude": 41.8802171
      },
      "url": "https://www.yelp.com/biz/designs-by-rosa-chicago",
      "categories": [
        {
          "alias": "florists",
          "title": "Florists"
        }
      ],
      "name": "Designs by Rosa",
      "image_url": "http://s3-media1.fl.yelpcdn.com/bphoto/KGdvqraJ0lHUDzP_id9uqQ/o.jpg",
      "id": "designs-by-rosa-chicago",
      "phone": "+13127590607",
      "review_count": 32,
      "price": "$$",
      "rating": 4
    },
    {
      "location": {
        "address2": "",
        "address1": "1718 N Wells St",
        "country": "US",
        "city": "Chicago",
        "state": "IL",
        "address3": "",
        "zip_code": "60614"
      },
      "coordinates": {
        "longitude": -87.6349564,
        "latitude": 41.9132957
      },
      "url": "https://www.yelp.com/biz/green-chicago",
      "categories": [
        {
          "alias": "florists",
          "title": "Florists"
        }
      ],
      "name": "Green",
      "image_url": "http://s3-media1.fl.yelpcdn.com/bphoto/qzIQviRUmlejDlMFdLyCfA/o.jpg",
      "id": "green-chicago",
      "phone": "+13122662806",
      "review_count": 29,
      "price": "$$$",
      "rating": 4.5
    },
    {
      "location": {
        "address2": "",
        "address1": "312 S Dearborn St",
        "country": "US",
        "city": "Chicago",
        "state": "IL",
        "address3": "",
        "zip_code": "60604"
      },
      "coordinates": {
        "longitude": -87.6295484185242,
        "latitude": 41.8778062061505
      },
      "url": "https://www.yelp.com/biz/a-new-leaf-chicago-2",
      "categories": [
        {
          "alias": "florists",
          "title": "Florists"
        }
      ],
      "name": "A New Leaf",
      "image_url": "http://s3-media3.fl.yelpcdn.com/bphoto/b8REQRVcSa4SX_RnD_ktaQ/o.jpg",
      "id": "a-new-leaf-chicago-2",
      "phone": "+13124279097",
      "review_count": 34,
      "price": "$$$",
      "rating": 4
    },
    {
      "location": {
        "address2": "",
        "address1": "1645 N Wells St",
        "country": "US",
        "city": "Chicago",
        "state": "IL",
        "address3": "",
        "zip_code": "60614"
      },
      "coordinates": {
        "longitude": -87.6345901454384,
        "latitude": 41.9124372119695
      },
      "url": "https://www.yelp.com/biz/a-new-leaf-chicago",
      "categories": [
        {
          "alias": "florists",
          "title": "Florists"
        },
        {
          "alias": "venues",
          "title": "Venues & Event Spaces"
        }
      ],
      "name": "A New Leaf",
      "image_url": "http://s3-media3.fl.yelpcdn.com/bphoto/0ewF4bs6GzGlE5XfGtiYhQ/o.jpg",
      "id": "a-new-leaf-chicago",
      "phone": "+13126421576",
      "review_count": 71,
      "price": "$$$",
      "rating": 4
    },
    {
      "location": {
        "address2": "",
        "address1": "1827 S Halsted",
        "country": "US",
        "city": "Chicago",
        "state": "IL",
        "address3": "",
        "zip_code": "60608"
      },
      "coordinates": {
        "longitude": -87.6465553790331,
        "latitude": 41.8573395162821
      },
      "url": "https://www.yelp.com/biz/blumgarten-and-co-chicago",
      "categories": [
        {
          "alias": "florists",
          "title": "Florists"
        }
      ],
      "name": "Blumgarten & Co",
      "image_url": "http://s3-media3.fl.yelpcdn.com/bphoto/rKWi5qZR3VAsVJIcS-KKHQ/o.jpg",
      "id": "blumgarten-and-co-chicago",
      "phone": "+13127709052",
      "review_count": 51,
      "price": "$$$",
      "rating": 4.5
    },
    {
      "location": {
        "address2": "",
        "address1": "40 W Lake St",
        "country": "US",
        "city": "Chicago",
        "state": "IL",
        "address3": "",
        "zip_code": "60601"
      },
      "coordinates": {
        "longitude": -87.6290981,
        "latitude": 41.8858849
      },
      "url": "https://www.yelp.com/biz/robert-daniels-florist-chicago",
      "categories": [
        {
          "alias": "florists",
          "title": "Florists"
        }
      ],
      "name": "Robert Daniels Florist",
      "image_url": "http://s3-media2.fl.yelpcdn.com/bphoto/uSYdOw1dAuF54evRUQqTpQ/o.jpg",
      "id": "robert-daniels-florist-chicago",
      "phone": "+13123320500",
      "review_count": 15,
      "price": "$$$",
      "rating": 3.5
    },
    {
      "location": {
        "address2": "Ste 3C",
        "address1": "212 N Sangamon St",
        "country": "US",
        "city": "Chicago",
        "state": "IL",
        "address3": "",
        "zip_code": "60607"
      },
      "coordinates": {
        "longitude": -87.65136,
        "latitude": 41.886169
      },
      "url": "https://www.yelp.com/biz/natural-beauties-floral-chicago-2",
      "categories": [
        {
          "alias": "florists",
          "title": "Florists"
        }
      ],
      "name": "Natural Beauties Floral",
      "image_url": "http://s3-media4.fl.yelpcdn.com/bphoto/tpy-loDkMkHUfXLR8y1__g/o.jpg",
      "id": "natural-beauties-floral-chicago-2",
      "phone": "+13122432690",
      "review_count": 23,
      "price": "$$",
      "rating": 4.5
    },
    {
      "location": {
        "address2": "Ste F-248",
        "address1": "2010 W Fulton St",
        "country": "US",
        "city": "Chicago",
        "state": "IL",
        "address3": "",
        "zip_code": "60612"
      },
      "coordinates": {
        "longitude": -87.6359125,
        "latitude": 41.9028369
      },
      "url": "https://www.yelp.com/biz/exquisite-designs-chicago-2",
      "categories": [
        {
          "alias": "florists",
          "title": "Florists"
        }
      ],
      "name": "Exquisite Designs",
      "image_url": "http://s3-media3.fl.yelpcdn.com/bphoto/pHmtl5EaWPRzt_dhJagPzA/o.jpg",
      "id": "exquisite-designs-chicago-2",
      "phone": "+17739753333",
      "review_count": 18,
      "price": "$$",
      "rating": 5
    },
    {
      "location": {
        "address2": "",
        "address1": "140 E Walton Pl",
        "country": "US",
        "city": "Chicago",
        "state": "IL",
        "address3": "",
        "zip_code": "60611"
      },
      "coordinates": {
        "longitude": -87.623405456543,
        "latitude": 41.9004135131836
      },
      "url": "https://www.yelp.com/biz/mangel-florists-chicago",
      "categories": [
        {
          "alias": "florists",
          "title": "Florists"
        }
      ],
      "name": "Mangel Florists",
      "image_url": "http://s3-media4.fl.yelpcdn.com/bphoto/39Bxy_rmW9HpMChAEpYxSA/o.jpg",
      "id": "mangel-florists-chicago",
      "phone": "+13126422001",
      "review_count": 6,
      "price": "$$$",
      "rating": 4
    },
    {
      "location": {
        "address2": "Unit 104",
        "address1": "855 W Blackhawk St",
        "country": "US",
        "city": "Chicago",
        "state": "IL",
        "address3": "",
        "zip_code": "60642"
      },
      "coordinates": {
        "longitude": -87.6506057,
        "latitude": 41.9083951
      },
      "url": "https://www.yelp.com/biz/vale-of-enna-chicago-2",
      "categories": [
        {
          "alias": "florists",
          "title": "Florists"
        }
      ],
      "name": "Vale Of Enna",
      "image_url": "http://s3-media3.fl.yelpcdn.com/bphoto/Ihz5PyDajRFDuTwAKyjGjg/o.jpg",
      "id": "vale-of-enna-chicago-2",
      "phone": "+17738093112",
      "review_count": 46,
      "price": "$$",
      "rating": 4
    },
    {
      "location": {
        "address2": "",
        "address1": "731 N La Salle Dr",
        "country": "US",
        "city": "Chicago",
        "state": "IL",
        "address3": "",
        "zip_code": "60654"
      },
      "coordinates": {
        "longitude": -87.632624655962,
        "latitude": 41.8957514315844
      },
      "url": "https://www.yelp.com/biz/la-salle-flowers-chicago",
      "categories": [
        {
          "alias": "florists",
          "title": "Florists"
        }
      ],
      "name": "La Salle Flowers",
      "image_url": "http://s3-media2.fl.yelpcdn.com/bphoto/ywG4v7BFxoL7RX7HGpd9pw/o.jpg",
      "id": "la-salle-flowers-chicago",
      "phone": "+13127873680",
      "review_count": 62,
      "price": "$$",
      "rating": 3
    },
    {
      "location": {
        "address2": "",
        "address1": "212 N Sangamon St",
        "country": "US",
        "city": "Chicago",
        "state": "IL",
        "address3": "",
        "zip_code": "60607"
      },
      "coordinates": {
        "longitude": -87.651361,
        "latitude": 41.886168
      },
      "url": "https://www.yelp.com/biz/oliver-dogwood-floral-company-chicago",
      "categories": [
        {
          "alias": "florists",
          "title": "Florists"
        }
      ],
      "name": "Oliver Dogwood Floral Company",
      "image_url": "http://s3-media1.fl.yelpcdn.com/bphoto/HJDTjDfeNCIQ2YMfsd4UNg/o.jpg",
      "id": "oliver-dogwood-floral-company-chicago",
      "phone": "+13124797694",
      "review_count": 9,
      "price": "$$",
      "rating": 5
    },
    {
      "location": {
        "address2": "250 E Superior",
        "address1": "Prentice Women's Hospital",
        "country": "US",
        "city": "Chicago",
        "state": "IL",
        "address3": "",
        "zip_code": "60611"
      },
      "coordinates": {
        "longitude": -87.6210355013609,
        "latitude": 41.8958158046007
      },
      "url": "https://www.yelp.com/biz/ashland-addison-florist-chicago-3",
      "categories": [
        {
          "alias": "florists",
          "title": "Florists"
        }
      ],
      "name": "Ashland-Addison Florist",
      "image_url": "http://s3-media2.fl.yelpcdn.com/bphoto/4jXzMQBwwOu_wf9Pw2XonQ/o.jpg",
      "id": "ashland-addison-florist-chicago-3",
      "phone": "+13124727673",
      "review_count": 21,
      "price": "$$",
      "rating": 4.5
    },
    {
      "location": {
        "address2": "",
        "address1": "1818 N Wells St",
        "country": "US",
        "city": "Chicago",
        "state": "IL",
        "address3": "",
        "zip_code": "60614"
      },
      "coordinates": {
        "longitude": -87.6350076,
        "latitude": 41.9153071
      },
      "url": "https://www.yelp.com/biz/a-new-leaf-chicago-4",
      "categories": [
        {
          "alias": "florists",
          "title": "Florists"
        }
      ],
      "name": "A New Leaf",
      "image_url": "http://s3-media4.fl.yelpcdn.com/bphoto/Fcjx751lZMM09AFyxwhCvw/o.jpg",
      "id": "a-new-leaf-chicago-4",
      "phone": "+13126428553",
      "review_count": 83,
      "price": "$$",
      "rating": 4
    },
    {
      "location": {
        "address2": "",
        "address1": "630 W Webster Ave",
        "country": "US",
        "city": "Chicago",
        "state": "IL",
        "address3": "",
        "zip_code": "60614"
      },
      "coordinates": {
        "longitude": -87.6450576782227,
        "latitude": 41.9220733642578
      },
      "url": "https://www.yelp.com/biz/suzanne-cummings-flowers-chicago",
      "categories": [
        {
          "alias": "florists",
          "title": "Florists"
        }
      ],
      "name": "Suzanne Cummings Flowers",
      "image_url": "http://s3-media4.fl.yelpcdn.com/bphoto/1NaUGbwrD9gZTvUaxUA7Kw/o.jpg",
      "id": "suzanne-cummings-flowers-chicago",
      "phone": "+18728024628",
      "review_count": 9,
      "price": "$$$$",
      "rating": 4.5
    },
    {
      "location": {
        "address2": "",
        "address1": "500 W Madison St",
        "country": "US",
        "city": "Chicago",
        "state": "IL",
        "address3": "",
        "zip_code": "60661"
      },
      "coordinates": {
        "longitude": -87.6404699,
        "latitude": 41.88235
      },
      "url": "https://www.yelp.com/biz/bunches-to-go-chicago",
      "categories": [
        {
          "alias": "florists",
          "title": "Florists"
        }
      ],
      "name": "Bunches To Go",
      "image_url": "http://s3-media1.fl.yelpcdn.com/bphoto/s56olYVAvGu3nnSxQ-8irg/o.jpg",
      "id": "bunches-to-go-chicago",
      "phone": "+13128791000",
      "review_count": 1,
      "rating": 4
    }
  ]
}

**Comment by tylerswartz** [comment]
@galskari - I heard from someone at Yelp yesterday that there are making some updates to the open now filter, not sure if it's been released yet, but this could be causing you the issue. 

"price_filter" is changing to "price"
"open_now_filter" is changing to "open_now"

**Comment by tomelm** [comment]
@galskari @tylerswartz this is correct, we've recently pushed a change to rename both parameters. I'm updating the documentation now

(We've opened #42 to discuss this change)

**Comment by tomelm** [comment]
I've updated the documentation, let me know if you're still seeing any problems
