### ISSUE TITLE
yelp api v3

### ISSUE THREAD

**Issue by nikitaturakhia24** [Yelp/yelp-api-v3#45]
Hello,

I am working on yelp api v3 and I am facing problem in sending request url format. After getting access_token
I am sending request in this format : "https://api.yelp.com/v3/businesses/search?term=delis&latitude=37.786882&longitude=-122.399972&access_token=my access_tokenid"
and I am getting error that token_missing.

Please let me know what is the problem here.

**Comment by tomelm** [comment]
Hey @nikitaturakhia24, you need to pass the access token as a header parameter, not a query parameter.

**Comment by nikitaturakhia24** [comment]
And how can I do it??
I mean can you please tell me how to pass as a header parameter?
I am new in this coding

**Comment by nikitaturakhia24** [comment]
hey @tomelm thanks for the help but can you please tell me that  how to pass access_token as a header parameter?
I am new in this coding

**Comment by NikitaTurakhia** [comment]
hey thanks @tomelm  i got the answer. Thanks again :)

**Comment by tomelm** [comment]
@NikitaTurakhia sure thing! Let me know if you have any other problems

**Comment by nikitaturakhia24** [comment]
Sure.. @tomelm :)

**Comment by chribsen** [comment]
Unfortunately, I'm still having issues understanding the documentation.
I've tried to pass my token the following ways, but I'm still receiving `MISSING_TOKEN`.

HTTP Headers:
`Authorization: mytoken123`
or
HTTP Headers:
`Authorization: Bearer mytoken123`

The method above seems to follow the documentation: _To authenticate API calls with the access token, set the Authorization HTTP header value as Bearer access_token._ (https://www.yelp.com/developers/documentation/v3/get_started)

**Comment by compworkmail** [comment]
I have the same question - I am receiving {"error": {"description": "An access token must be supplied in order to use this endpoint.", "code": "TOKEN_MISSING"}} all the time, but I added an access_token to header:
            $response = $client->request(
                'get', 
                'https://' . $this->apiHost . $reviewsPath,
                [
                    'headers' => ['access_token' => $encodedRes['access_token']],
                ]
            );

**Comment by mittonk** [comment]
@chribsen , @compworkmail : In CURL syntax, aim for:
```
curl \
  -X GET \
  -H "Authorization: Bearer TokenYouGotFromOauth2TokenEndpoint" \
  "https://api.yelp.com/v3/businesses/search?term=food&location=boston"
```
Note that the header is "Authorization" (not "access_token") and the value includes "Bearer " before your actual token.

**Comment by NikitaTurakhia** [comment]
hey @chribsen you have to pass your toke as a header like this: 
client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", your access_token);

**Comment by chribsen** [comment]
@mittonk Thanks!
Turns out that I was using an old token (probably from the v2 API). Fixed it simply by re-authenticating with my app.

I have two minor suggestions:
* Better error messages: The primary reason I didn't figure this out was because the endpoint returned `HTTP 500 Internal error`. A simple `HTTP 401 Unauthorized` preferably with a meaningful error code would be great!
* The documentation seems to use different words for the same things. I'm guessing that `client_id` and `App ID` refers to the same thing.

With that said, I really appreciate the work that you guys are doing!

**Comment by mittonk** [comment]
Awesome, that explains it.

Agreed, replacing all 500s with useful error messages is one of my projects right now.

We'll have a look at that wording.

**Comment by NikitaTurakhia** [comment]
Hello,

I am using yelp API v3.
When I run business API with term restaurant, I am getting only 14 businesses instead of 20 and when I run API with term pizza I am getting only 3 businesses.
Please help me with this issue.

Thank you,
Nikita

Get Outlook for iOS<https://aka.ms/o0ukef>




On Fri, Aug 26, 2016 at 2:08 PM -0400, "nikitaturakhia24" <notifications@github.com<mailto:notifications@github.com>> wrote:


Sure.. @tomelm<https://github.com/tomelm> :)

-

**Comment by mittonk** [comment]
@NikitaTurakhia : That sounds like a different issue, let's discuss over in #87 .  

(If you read Github via email rather than as a webpage: You'll get a different email thread called "[Yelp/yelp-fusion] Getting fewer than 20 results in search (#87)", let's keep talking on that.)

**Comment by NikitaTurakhia** [comment]
@mittonk  sure.

**Comment by jagadeesh583** [comment]
https://api.yelp.com/v3/businesses/search?term=dinner&location=San%20Francisco%2C%20CA&limit=3 with headers{Authorization=G*****************************************************888, token_type=Bearer

**Comment by mittonk** [comment]
@jagadeesh583 : Try
```
headers{Authorization="Bearer G******888"}
```
using your notation.

If you have any more problems, please open a fresh issue and we can discuss there!

**Comment by jagadeesh583** [comment]
@mittonk  thanks 

there is a problem in my code.
fixed now.

	public String uelpApiCall(String term, String location) {
		String getRequestPath = API_HOST + SEARCH_PATH + "?term=" + term + "+&location=" + location;
		HttpResponse<JsonNode> response = null;
		try {
			response = Unirest.get(getRequestPath)
					.header("authorization",
							"Bearer *****************************************************")
					.asJson();
		} catch (UnirestException e) {
			e.printStackTrace();
		}
		return response.toString();
	}

**Comment by jagadeesh583** [comment]
`
		if (location != null) {
			location = location.replace(" ", "+");
		}
		String getRequestPath = API_HOST + SEARCH_PATH + "?term=" + term + "+&location=" + location;
		HttpResponse<JsonNode> response = null;
		try {
			response = Unirest.get(getRequestPath)
					.header("authorization",
							"Bearer GO6xNvaKyG8xkzqPriGbSC738_J5V5vCnbOle1Q_98gvsLnIGl3j-wRlHfjXZJo85j6-P7deDI3o8YHdTSeLjRVH81pDSg6Ecqhf0vwLA1Kn19bn4luhnUJDaVrjWHYx")
					.asJson();
		} catch (UnirestException e) {
			e.printStackTrace();
		}
		LOGGER.info("" + response.getBody());
		return response.toString();
	`

**Comment by jagadeesh583** [comment]
following code is for generating a new token with expire time 180 days.

try {
			HttpResponse<JsonNode> responseToken = Unirest.post(TOKEN_GENERATAION_URL)
					.header("content-type", "application/x-www-form-urlencoded").body("client_id=" + CONSUMER_KEY
							+ "&client_secret=" + CONSUMER_SECRET + "&grant_type=client_credentials&=")
					.asJson();
			if (responseToken.getStatus() == 200) {
				JSONObject json = responseToken.getBody().getObject();
				TOKEN_TYPE = json.get("token_type").toString();
				TOKEN_SECRET = json.get("access_token").toString();
				TOken_EXPIRY_TIME = json.getString("expires_in");
			} else {
				LOGGER.info(">>>>> token generation failed " + responseToken.getStatus());
			}
		} catch (UnirestException e) {
			e.printStackTrace();
		} catch (JSONException e) {
			e.printStackTrace();
		}

**Comment by rchzh** [comment]
Today I also having same problem. I wrote small app to call https://api.yelp.com/v3/businesses/search?term=MY_TERM&limit=20&location=USA endpoint. When tested it in postman I receive response just fine.

But when try to execute GET method from app - receive message "An access token must be supplied in order to use this endpoint."

Request looks like : 

`{Method: GET, RequestUri: 'https://api.yelp.com/v3/businesses/search?term=MY_TERM&limit=20&location=USA', Version: 1.1, Content: <null>, Headers:
{
  Authorization: Bearer dLyWo7....
}}`

For me seems like correct request...

Thanks for any help

**Comment by Attriumph** [comment]
could you give a specific request url in Yelp doucment. I think it will be very helpful.

**Comment by morganb826** [comment]
Hi I am using an https authorization header and I am still getting a Error: {"error": {"code": "TOKEN_MISSING", "description": "An access token must be supplied in order to use this endpoint."}} | error | Unauthorized error. Here is my code:


            var strURL = "https://cors-anywhere.herokuapp.com/https://api.yelp.com/v3/businesses/search?location=boston";

                $("#display").html("");

                $.ajax({
                    type: "GET",
                    header: {
                        "Authorization":"Bearer h3*****x"
                    },
                    url: strURL,
