### ISSUE TITLE
CLIENT_ERROR response

### ISSUE THREAD

**Issue by cdbeshore** [Yelp/yelp-api-v3#48]
Hi! I've been trying to get the v3 API working and keep hitting this error. This is on iOS in Swift. I have tried both simulator and device.

Success: true
Response String: Optional("{\"error\": {\"code\": \"CLIENT_ERROR\", \"description\": \"Not Found\"}}")

It is authenticating, but getting CLIENT_ERROR. I haven't been able to nail down why. I have tried a couple of ways, one with Alamofire and another with this OAuth2 framework. https://github.com/p2/OAuth2

Same response for both. Anybody have any insight to point me in the right direction?

Here's my Alamofire code:

```
let parameters = [
            "client_id": clientId,
            "client_secret": clientSecret,
            "grant_type": "client_credentials"
        ]
        
        Alamofire.request(.POST, "https://api.yelp.com/oauth2/token", parameters: parameters)
            .responseString { response in
                print("Success: \(response.result.isSuccess)")
                print("Response String: \(response.result.value)")
        }
```
returns this:
Success: true
Response String: Optional("{\"error\": {\"code\": \"CLIENT_ERROR\", \"description\": \"Not Found\"}}")

The only thing I have been able to find is this explanation for token errors:
CLIENT_ERROR: "An authorization error occurring on the client rather than the server. For example, due to client misconfiguration."

**Comment by tomelm** [comment]
Hey @cdbeshore could you give me your client_id? Let me check the logs to see if I can figure out what's up.

**Comment by cdbeshore** [comment]
Thanks tomelm. I emailed it to your gmail. I appreciate your help.

**Comment by tomelm** [comment]
Got it! Will let you know what I find

**Comment by cdbeshore** [comment]
Hi tomelm. Have you had a chance to check out the logs?  Appreciate your feedback!

**Comment by tomelm** [comment]
Hey! Sorry about that. I couldn't find anything in the logs :(

Do you know if that's submitting the data as json or as x-www-urlform-encoded? We only support the latter for the token endpoints.

**Comment by cdbeshore** [comment]
tomelm. Thanks for checking. I added that to the header, though I think it was being sent already through Alamofire. No luck, still getting the same error. I've tried several different ways to no luck. Below is my latest attempt using only iOS frameworks. Can't figure out what I'm doing wrong!

```
let clientId = "8ae913c685556e73a16f"
let clientSecret = "QMUCSIYchm9Wdur05e5zxs8GX6yptqGOr8vVXrMUIcJdcbffmXwNEonrABQ2lvMn"
let tokenURL = "https://api.yelp.com/oauth2/token"
let grantType = "client_credentials"


let url = NSURL(string: tokenURL as String );

let session = NSURLSession(configuration: NSURLSessionConfiguration.defaultSessionConfiguration())

let request = NSMutableURLRequest(URL: NSURL(string: tokenURL)!)
request.HTTPMethod = "POST";
request.HTTPShouldHandleCookies = true
request.setValue("application/x-www-form-urlencoded", forHTTPHeaderField: "Content-Type")


let postString = "client_id=" + clientId + "&client_secret=" + clientSecret + "&grant_type=" + grantType
request.HTTPBody = postString.dataUsingEncoding(NSUTF8StringEncoding)

let task: NSURLSessionDataTask = session.dataTaskWithRequest(request) { (data, response, error) -> Void in
    if let data = data {
        let response = NSString(data: data, encoding: NSUTF8StringEncoding)
        print(response)
    }
}
task.resume()
```

**Comment by cdbeshore** [comment]
I have found the problem. I had a digit missing from my client id. It pays to look over everything closely!

**Comment by tomelm** [comment]
@cdbeshore glad you got it figured out! And now we know why it wasn't showing up in the logs :D
