### ISSUE TITLE
Add phone to /businesses/{id} endpoint

### ISSUE THREAD

**Issue by mars271** [Yelp/yelp-api-v3#5]
I see that phone is available in the `/businesses/search` endpoint but not in `/businesses/{id}`.  It would be nice to have this field in `/businesses/{id}` so that it would be accessible if using other endpoints to find a location like `/autocomplete` or `/transactions/{transaction_type}/search` which don't return phone.

**Comment by tomelm** [comment]
Good catch @mars271! We've ticketed this internally too and will follow up with a fix

**Comment by tomelm** [comment]
@mars271 I've pushed a fix for this, phone numbers should be appearing now.

**Comment by guangyang** [comment]
@tomelm, could you also update the API reference if you haven't?

**Comment by tomelm** [comment]
@guangyang done, thanks for the reminder!
