### ISSUE TITLE
[Feature] reviews need a stable unique id

### ISSUE THREAD

**Issue by wpohl** [Yelp/yelp-api-v3#52]
The url can't be used for that because the url may change, and changed in the last weeks.

Formerly it was something like 
* https://www.yelp.com/biz/joe-allen-london?hrid=a4R3PAMIxAtXC5VyilbznA 

now it is
* https://www.yelp.com/biz/joe-allen-london?hrid=a4R3PAMIxAtXC5VyilbznA&adjust_creative=Oo61i4rcBT69teb4Pd-iLw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=Oo61i4rcBT69teb4Pd-iLw@yelp.com.enfore.test

We should agree that the hrid query param identifies the review.

**Comment by tomelm** [comment]
Hey @wpohl, the hrid parameter does uniquely identify the review, that will not change as it's tied to the review.
