### ISSUE TITLE
Business endpoints stopped returning prices

### ISSUE THREAD

**Issue by smithtim** [Yelp/yelp-api-v3#700]
### Description

The business details endpoint (`/v3/businesses/{id}`) and business search endpoint (`/v3/businesses/search`) are supposed to return a `price` field containing a value like `$$`.  They used to do that, but seem to have stopped within the last few months.  The `price` field is no longer being returned for any businesses, as far as I can tell.

Can anyone reproduce this?  Is it a bug, or was the API changed recently?  The documentation still shows the `price` field.

### Endpoints
`https://api.yelp.com/v3/businesses/{id}`
`https://api.yelp.com/v3/businesses/search`

### Response
* **expected:** a JSON response with business fields like `id`, `name`, and `location`, including `price`
* **actual:** the above, but `price` is missing

**Comment by ericestes** [comment]
I'm seeing the same issue.

**Comment by rockdog** [comment]
Hi @smithtim, we are currently looking into this. I'll keep you posted.

**Comment by rockdog** [comment]
Hi @smithtim, we've just deployed a fix for this issue. Feel free to re-open if you continue to see this problem.
