### ISSUE TITLE
Reviews API Always Returns "Resource could not be found"

### ISSUE THREAD

**Issue by ahmad-hossain** [Yelp/yelp-api-v3#701]
**Note:** _Do not post any API keys or secrets or they will be rotated_
<br><hr>

## Overview
- **Client ID:** VQTO1d8iD6iEq2DKAbop4g
- **Issue type:** bug/help
- **Summary:** Unable to retrieve reviews for business: "Resource could not be found"
- **Platform:** Tested using CURL from Yelp docs

## Description
**Goal:** Retrieve the top review of a given business
**Problem:** When calling the Reviews API for any business, I receive a 404 "Resource could not be found" error.
**What I have tried:**
* Changing `sort_by`
* Trying business aliases instead of business id
* Trying business ids/aliases for several different businesses
* Adjusting the `limit`: Tried multiple values between 0 and 20

**Note:** I am retrieving business ids/aliases via the [businesses search API](https://docs.developer.yelp.com/reference/v3_business_search), and can successfully retrieve businesses using CURL with this API.

**Sample Request:**
```
curl --request GET \
     --url 'https://api.yelp.com/v3/businesses/veq1Bl1DW3UWMekZJUsG1Q/reviews?limit=1&sort_by=yelp_sort' \
     --header 'Authorization: Bearer MY_API_KEY_HERE' \
     --header 'accept: application/json'
```

## More information
_(Fill this section out if applicable (for things like bugs or questions. Do not post any API keys or secrets.))_

### Endpoint
Fusion Search API

### Parameters or Sample Request
```
https://api.yelp.com/v3/businesses/veq1Bl1DW3UWMekZJUsG1Q/reviews?limit=1&sort_by=yelp_sort
```

### Response
```
{
  "error": {
    "code": "NOT_FOUND",
    "description": "Resource could not be found."
  }
}
```

## Extra information
_(Anything else you that you think might help us better resolve this. Do not post any API keys or secrets.)_

**Comment by rockdog** [comment]
Hi @ahmad-hossain, access to the reviews endpoint is not part of your plan. More details can be found here: https://docs.developer.yelp.com/page/start-your-free-trial

**Comment by ahmad-hossain** [comment]
Silly me, thank you!
