### ISSUE TITLE
Review api always return satus 404

### ISSUE THREAD

**Issue by zohaib5424** [Yelp/yelp-api-v3#702]
## Description
i am try to use review api but they always return false don't understand the problem
### Endpoint
Reviews api

### Parameters or Sample Request
https://api.yelp.com/v3/businesses/oK_SLmmAVQg3meguh7LrIA/reviews?limit=20&sort_by=yelp_sort

### Response
{
  "error": {
    "code": "NOT_FOUND",
    "description": "Resource could not be found."
  }
}

**Comment by rockdog** [comment]
Hi @zohaib5424, if you just recently signed up for a developer account it is very likely that your plan doesn't allow access to the reviews endpoint. More details can be found here: https://docs.developer.yelp.com/page/start-your-free-trial.

**Comment by bizmate** [comment]
It looks like Yelp does not want to get free advertising from third parties anymore. I will personally discourage the use of Yelp from now on the basis of:
- asking to pay for the data when you get free promotion is quite greedt
- the APIs do not have any webhooks or notifications for data changes so data needs to be checked multiple times maybe on a daily basis if you want to keep the data consistent
- even with the request for payment you still limit access to 3 reviews :) WOW

With the above is very difficult to keep a dataset consistent and provide the free traffic

**Comment by maininformer** [comment]
> Hi [@zohaib5424](https://github.com/zohaib5424), if you just recently signed up for a developer account it is very likely that your plan doesn't allow access to the reviews endpoint. More details can be found here: https://docs.developer.yelp.com/page/start-your-free-trial.

I know you probably did not make this decision, but WOW. 

300 a month for 3 reviews!

# Edit

Lol

![Image](https://github.com/user-attachments/assets/b2b6b34a-3c8a-4446-851a-a7e81c96bb47)
